Repository jhenriquelc/VelocityVanguards-2024.2, pull requests merged in 2025-01, with the labels that each got.

#33 Criar DER
  Banco de Dados/CREATE.sql
  Banco de Dados/DER.png
  Banco de Dados/README.md
  README.md
Labels: documentation

#60 Merge Supremo
  Prototipacao/WireframeLandingPage.jpeg
  Prototipacao/WireframeProductPage.jpeg
  Site/package.json
  Site/pnpm-lock.yaml
  Site/src/lib/CardsVendaEmDestaque.svelte
  Site/src/lib/ContatoProduto.svelte
  Site/src/lib/DadosDoImovel.svelte
  Site/src/lib/DescricaoImovel.svelte
  Site/src/lib/Filtros.svelte
  Site/src/lib/LocalizacaoImovel.svelte
  Site/src/lib/PrecoImovelProductPage.svelte
  Site/src/lib/VvHeader.svelte
  Site/src/lib/VvHero.svelte
  Site/src/lib/db.js
  Site/src/routes/+layout.svelte
  Site/src/routes/+page.server.js
  Site/src/routes/+page.svelte
  Site/src/routes/admin/+page.server.js
  Site/src/routes/admin/+page.svelte
  Site/src/routes/admin/dashboard/+page.server.js
  Site/src/routes/admin/dashboard/+page.svelte
  Site/src/routes/api/+server.js
  Site/src/routes/contato/+page.svelte
  Site/src/routes/imoveis/+page.server.js
  Site/src/routes/imoveis/+page.svelte
  Site/src/routes/imoveis/[id]/+page.server.js
  Site/src/routes/imoveis/[id]/+page.svelte
  Site/src/routes/sobre/+page.svelte
  Site/static/1/imagem0.jpg
  Site/static/1/imagem1.jpg
  Site/static/1/imagem2.jpg
  Site/static/1/imagem3.jpg
  Site/static/1/imagem4.jpg
  Site/static/imagem.jpg
  Site/static/imagem2.jpg
  Site/tailwind.config.ts
Labels: enhancement, help wanted

#52 Criar um footer
  Site/src/lib/VvFooter.svelte
  Site/src/lib/index.ts
  Site/src/routes/+page.svelte
Labels: enhancement, good first issue
